SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY  AS B ON A.CAR_ID = B.CAR_ID
WHERE DATE(START_DATE) BETWEEN '2022-10-01' AND '2022-10-31'
AND CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC