SELECT SUM(C.SCORE) as SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT AS A
LEFT JOIN HR_EMPLOYEES AS B ON A.DEPT_ID = B.DEPT_ID
LEFT JOIN HR_GRADE AS C ON B.EMP_NO = C.EMP_NO

GROUP BY B.EMP_NAME, C.EMP_NO, B.POSITION, B.EMAIL
ORDER BY SUM(C.SCORE) DESC
LIMIT 1